cors:
  allowed-origins:
    - "http://localhost:3000"
    - "http://localhost:3001"
    - "http://localhost:4200"
  allowed-methods:
    - "GET"
    - "POST"
    - "PUT"
    - "DELETE"
    - "OPTIONS"
    - "PATCH"
  allowed-headers:
    - "*"
  exposed-headers:
    - "Authorization"
    - "Content-Type"
    - "X-Total-Count"
  allow-credentials: true
  max-age: 3600 