# Development Environment Configuration
spring:
  datasource:
    hikari:
      maximum-pool-size: 15
      minimum-idle: 3
      driver-class-name: org.postgresql.Driver
      connection-timeout: 30000  # 30 seconds
      idle-timeout: 600000  # 10 minutes
      max-lifetime: 1800000  # 30 minutes

     # Test configuration for PostgreSQL with Testcontainers
    datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:ramsys_db}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME:ramsys}
    password: ${DB_PASSWORD:ramsys}

  # Show SQL queries in development
  jpa:
    hibernate:
      ddl-auto: validate  # Use Liquibase for schema management
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
        
  # Liquibase configuration
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    drop-first: true  # Drop and recreate schema for each test run
          
  # Disable unnecessary features in tests
  cloud:
    config:
      enabled: false
  config:
    import: "optional:file:.env[.properties]"

# Logging for tests
logging:
  level:
    com.ramsys: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.cache: DEBUG
    org.springframework.transaction: DEBUG

testcontainers:
      reuse:
        enable: true
# Swagger/OpenAPI enabled in dev
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    

# Development JWT - Shorter expiration for testing
app:
  cors:
    allowed-origins:
      - "http://localhost:3000"
      - "http://localhost:3001"
      - "http://localhost:4200"
      - "https://app.ramsys-reinsurance.com"
      - "https://*.lovableproject.com"
      - "https://lovableproject.com"
  jwt:
    expiration: 36000 # 10 hour for development
  security:
    cookie-secure: false

# Error handling - Show stack traces in dev
server:
  error: # on production this is set to never on application-prod.yml
    include-stacktrace: always
    include-exception: true
  ssl:
    enabled: true
    key-store: classpath:keystore-dev.p12
    key-store-password: password
    key-store-type: PKCS12
    key-alias: ramsys-dev
  port: 8443

  security:
    oauth2:
      resourceserver:
        jwt:
          public-key-location: classpath:public-key.pem
