# Staging Environment Configuration
spring:
  # Staging database settings
  datasource:
    hikari:
      maximum-pool-size: 15
      minimum-idle: 3
      
  # Moderate logging for staging
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        generate_statistics: true
        
# Staging logging
logging:
  level:
    root: INFO
    com.ramsys: DEBUG
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.hibernate.SQL: INFO
    
# Actuator - More endpoints than production
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,loggers,caches
        
# Swagger enabled for staging testing
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    
# Staging CORS
cors:
  allowed-origins: ${STAGING_ALLOWED_ORIGINS:https://staging.ramsys-reinsurance.com,http://localhost:3000}
  
# Staging JWT
app:
  jwt:
    expiration: 43200 # 12 hours
    
# Error handling - Moderate detail
server:
  error:
    include-stacktrace: on_param
    include-exception: false 