global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'ramsys-monitor'

scrape_configs:
  - job_name: 'ramsys-backend'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['app:8080']
        labels:
          application: 'ramsys-backend'
          environment: 'docker'
    
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
        labels:
          database: 'ramsys_r1'
          
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
        labels:
          instance: 'docker-host' 